# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8f99d32d-e667-4f1f-bce5-42680912618c";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:1" "discard=async" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8f99d32d-e667-4f1f-bce5-42680912618c";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:1" "discard=async" "noatime" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/8f99d32d-e667-4f1f-bce5-42680912618c";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:1" "discard=async" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/8f99d32d-e667-4f1f-bce5-42680912618c";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd:1" "discard=async" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8B2A-5EC8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/hdd" =
    { device = "/dev/disk/by-uuid/01ed2331-80da-4480-b6ab-f14826f9bba1";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fb13c494-6ebd-462e-89c7-06b5bb5264fa"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
